// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.30.2
// source: proto/yoconf.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Chunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	InUse         bool                   `protobuf:"varint,3,opt,name=InUse,proto3" json:"InUse,omitempty"`
	Project       string                 `protobuf:"bytes,4,opt,name=Project,proto3" json:"Project,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chunk) Reset() {
	*x = Chunk{}
	mi := &file_proto_yoconf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chunk) ProtoMessage() {}

func (x *Chunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yoconf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chunk.ProtoReflect.Descriptor instead.
func (*Chunk) Descriptor() ([]byte, []int) {
	return file_proto_yoconf_proto_rawDescGZIP(), []int{0}
}

func (x *Chunk) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *Chunk) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Chunk) GetInUse() bool {
	if x != nil {
		return x.InUse
	}
	return false
}

func (x *Chunk) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

type Resp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resp) Reset() {
	*x = Resp{}
	mi := &file_proto_yoconf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yoconf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_proto_yoconf_proto_rawDescGZIP(), []int{1}
}

func (x *Resp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RollOnRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollOnRequest) Reset() {
	*x = RollOnRequest{}
	mi := &file_proto_yoconf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollOnRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollOnRequest) ProtoMessage() {}

func (x *RollOnRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yoconf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollOnRequest.ProtoReflect.Descriptor instead.
func (*RollOnRequest) Descriptor() ([]byte, []int) {
	return file_proto_yoconf_proto_rawDescGZIP(), []int{2}
}

func (x *RollOnRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *RollOnRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Project       string                 `protobuf:"bytes,1,opt,name=Project,proto3" json:"Project,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=Version,proto3" json:"Version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_proto_yoconf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_yoconf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_proto_yoconf_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteRequest) GetProject() string {
	if x != nil {
		return x.Project
	}
	return ""
}

func (x *DeleteRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_yoconf_proto protoreflect.FileDescriptor

const file_proto_yoconf_proto_rawDesc = "" +
	"\n" +
	"\x12proto/yoconf.proto\"e\n" +
	"\x05Chunk\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\tR\x04Data\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\x05R\aVersion\x12\x14\n" +
	"\x05InUse\x18\x03 \x01(\bR\x05InUse\x12\x18\n" +
	"\aProject\x18\x04 \x01(\tR\aProject\" \n" +
	"\x04Resp\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\"C\n" +
	"\rRollOnRequest\x12\x18\n" +
	"\aProject\x18\x01 \x01(\tR\aProject\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\x05R\aVersion\"C\n" +
	"\rDeleteRequest\x12\x18\n" +
	"\aProject\x18\x01 \x01(\tR\aProject\x12\x18\n" +
	"\aVersion\x18\x02 \x01(\x05R\aVersion2m\n" +
	"\x06YoConf\x12\x1c\n" +
	"\vCreateChunk\x12\x06.Chunk\x1a\x05.Resp\x12\x1f\n" +
	"\x06RollOn\x12\x0e.RollOnRequest\x1a\x05.Resp\x12$\n" +
	"\vDeleteChunk\x12\x0e.DeleteRequest\x1a\x05.RespB\x06Z\x04./pbb\x06proto3"

var (
	file_proto_yoconf_proto_rawDescOnce sync.Once
	file_proto_yoconf_proto_rawDescData []byte
)

func file_proto_yoconf_proto_rawDescGZIP() []byte {
	file_proto_yoconf_proto_rawDescOnce.Do(func() {
		file_proto_yoconf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_yoconf_proto_rawDesc), len(file_proto_yoconf_proto_rawDesc)))
	})
	return file_proto_yoconf_proto_rawDescData
}

var file_proto_yoconf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_yoconf_proto_goTypes = []any{
	(*Chunk)(nil),         // 0: Chunk
	(*Resp)(nil),          // 1: Resp
	(*RollOnRequest)(nil), // 2: RollOnRequest
	(*DeleteRequest)(nil), // 3: DeleteRequest
}
var file_proto_yoconf_proto_depIdxs = []int32{
	0, // 0: YoConf.CreateChunk:input_type -> Chunk
	2, // 1: YoConf.RollOn:input_type -> RollOnRequest
	3, // 2: YoConf.DeleteChunk:input_type -> DeleteRequest
	1, // 3: YoConf.CreateChunk:output_type -> Resp
	1, // 4: YoConf.RollOn:output_type -> Resp
	1, // 5: YoConf.DeleteChunk:output_type -> Resp
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_yoconf_proto_init() }
func file_proto_yoconf_proto_init() {
	if File_proto_yoconf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_yoconf_proto_rawDesc), len(file_proto_yoconf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_yoconf_proto_goTypes,
		DependencyIndexes: file_proto_yoconf_proto_depIdxs,
		MessageInfos:      file_proto_yoconf_proto_msgTypes,
	}.Build()
	File_proto_yoconf_proto = out.File
	file_proto_yoconf_proto_goTypes = nil
	file_proto_yoconf_proto_depIdxs = nil
}
